# Generated by Django 5.1.15 on 2025-12-26 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('trendyol_order_id', models.CharField(db_index=True, max_length=100, verbose_name='Trendyol Sipariş ID')),
                ('trendyol_order_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Sipariş Numarası')),
                ('order_date', models.DateTimeField(db_index=True, verbose_name='Sipariş Tarihi')),
                ('status', models.CharField(choices=[('Created', 'Oluşturuldu'), ('Picking', 'Hazırlanıyor'), ('Invoiced', 'Faturalandı'), ('Shipped', 'Kargoya Verildi'), ('Delivered', 'Teslim Edildi'), ('Cancelled', 'İptal'), ('Returned', 'İade'), ('UnDelivered', 'Teslim Edilemedi'), ('UnDeliveredAndReturned', 'Teslim Edilemedi ve İade')], db_index=True, max_length=50, verbose_name='Durum')),
                ('customer_id', models.CharField(blank=True, max_length=100, verbose_name='Müşteri ID')),
                ('cargo_company', models.CharField(blank=True, max_length=100, verbose_name='Kargo Şirketi')),
                ('cargo_tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Kargo Takip No')),
                ('cargo_provider_name', models.CharField(blank=True, max_length=100, verbose_name='Kargo Sağlayıcı')),
                ('shipment_package_id', models.CharField(blank=True, max_length=100, verbose_name='Gönderi Paket ID')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Kargoya Verilme Tarihi')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Teslim Tarihi')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Fatura Numarası')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Toplam Tutar')),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Toplam İndirim')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Ham Veri')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Senkronizasyon Tarihi')),
                ('last_modified_date', models.DateTimeField(blank=True, help_text="Trendyol'daki son değişiklik tarihi", null=True, verbose_name='Son Değişiklik Tarihi')),
                ('seller_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sellers.selleraccount', verbose_name='Satıcı Hesabı')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'db_table': 'orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trendyol_line_id', models.CharField(max_length=100, verbose_name='Trendyol Line ID')),
                ('barcode', models.CharField(db_index=True, max_length=100, verbose_name='Barkod')),
                ('product_code', models.CharField(blank=True, max_length=100, verbose_name='Model Kodu')),
                ('product_name', models.CharField(max_length=500, verbose_name='Ürün Adı')),
                ('product_size', models.CharField(blank=True, max_length=50, verbose_name='Beden')),
                ('product_color', models.CharField(blank=True, max_length=100, verbose_name='Renk')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Satış fiyatı (KDV dahil)', max_digits=12, verbose_name='Birim Fiyat')),
                ('original_price', models.DecimalField(decimal_places=2, default=0, help_text='İndirim öncesi fiyat', max_digits=12, verbose_name='Orijinal Fiyat')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='İndirim Tutarı')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, help_text='Trendyol komisyon oranı (%)', max_digits=5, verbose_name='Komisyon Oranı')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, help_text='Trendyol tarafından kesilen komisyon', max_digits=12, verbose_name='Komisyon Tutarı')),
                ('cargo_cost', models.DecimalField(decimal_places=2, default=0, help_text='Satıcıya yansıyan kargo maliyeti', max_digits=12, verbose_name='Kargo Maliyeti')),
                ('platform_service_fee', models.DecimalField(decimal_places=2, default=0, help_text='Trendyol platform hizmet ücreti', max_digits=12, verbose_name='Platform Hizmet Bedeli')),
                ('merchant_sku', models.CharField(blank=True, max_length=100, verbose_name='Satıcı SKU')),
                ('item_status', models.CharField(choices=[('active', 'Aktif'), ('cancelled', 'İptal'), ('returned', 'İade')], default='active', max_length=20, verbose_name='Kalem Durumu')),
                ('return_reason', models.CharField(blank=True, max_length=255, verbose_name='İade Nedeni')),
                ('is_calculated', models.BooleanField(default=False, help_text='Kar hesaplaması yapıldı mı?', verbose_name='Hesaplandı')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Ham Veri')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Sipariş')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Sipariş Kalemi',
                'verbose_name_plural': 'Sipariş Kalemleri',
                'db_table': 'order_items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['seller_account', 'order_date'], name='orders_seller__756b44_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['seller_account', 'status'], name='orders_seller__564732_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['trendyol_order_number'], name='orders_trendyo_813145_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'barcode'], name='order_items_order_i_5c3489_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['barcode'], name='order_items_barcode_edc117_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['item_status'], name='order_items_item_st_1f19ad_idx'),
        ),
    ]
