# Generated by Django 5.1.15 on 2025-12-26 23:03

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('seller_id', models.CharField(help_text="Trendyol Satıcı Panel'den alınan Satıcı ID", max_length=100, validators=[core.validators.validate_trendyol_seller_id], verbose_name='Satıcı ID')),
                ('api_key', models.TextField(help_text='Trendyol API anahtarı (şifreli saklanır)', verbose_name='API Anahtarı')),
                ('api_secret', models.TextField(help_text='Trendyol API secret (şifreli saklanır)', verbose_name='API Secret')),
                ('shop_name', models.CharField(max_length=255, verbose_name='Mağaza Adı')),
                ('shop_url', models.URLField(blank=True, verbose_name='Mağaza URL')),
                ('default_commission_rate', models.DecimalField(decimal_places=2, default=12.0, help_text='Kategori bazlı oran yoksa kullanılacak varsayılan komisyon (%)', max_digits=5, verbose_name='Varsayılan Komisyon Oranı')),
                ('default_cargo_cost', models.DecimalField(decimal_places=2, default=0, help_text='Varsayılan kargo maliyeti (KDV hariç, TL)', max_digits=10, verbose_name='Varsayılan Kargo Maliyeti')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sync_status', models.CharField(choices=[('idle', 'Beklemede'), ('syncing', 'Senkronize Ediliyor'), ('completed', 'Tamamlandı'), ('error', 'Hata')], default='idle', max_length=20, verbose_name='Senkronizasyon Durumu')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Senkronizasyon')),
                ('last_sync_order_date', models.DateTimeField(blank=True, help_text='Incremental sync için referans tarih', null=True, verbose_name='Son Senkronize Edilen Sipariş Tarihi')),
                ('last_sync_error', models.TextField(blank=True, verbose_name='Son Senkronizasyon Hatası')),
                ('total_orders_synced', models.PositiveIntegerField(default=0, verbose_name='Toplam Senkronize Sipariş')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Satıcı Hesabı',
                'verbose_name_plural': 'Satıcı Hesapları',
                'db_table': 'seller_accounts',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'seller_id')},
            },
        ),
        migrations.CreateModel(
            name='SellerSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Başladı'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], max_length=20, verbose_name='Durum')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sync_type', models.CharField(choices=[('full', 'Tam Senkronizasyon'), ('incremental', 'Artımlı Senkronizasyon'), ('manual', 'Manuel Senkronizasyon')], default='incremental', max_length=20, verbose_name='Senkronizasyon Tipi')),
                ('date_range_start', models.DateTimeField(blank=True, null=True, verbose_name='Tarih Aralığı Başlangıç')),
                ('date_range_end', models.DateTimeField(blank=True, null=True, verbose_name='Tarih Aralığı Bitiş')),
                ('orders_fetched', models.PositiveIntegerField(default=0)),
                ('orders_created', models.PositiveIntegerField(default=0)),
                ('orders_updated', models.PositiveIntegerField(default=0)),
                ('items_processed', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('seller_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='sellers.selleraccount')),
            ],
            options={
                'verbose_name': 'Senkronizasyon Logu',
                'verbose_name_plural': 'Senkronizasyon Logları',
                'db_table': 'seller_sync_logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
