# Generated by Django 5.1.15 on 2025-12-26 23:03

import core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('email', models.EmailField(error_messages={'unique': 'Bu email adresi zaten kayıtlı.'}, max_length=254, unique=True, verbose_name='Email Adresi')),
                ('first_name', models.CharField(max_length=150, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=150, verbose_name='Soyad')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Şirket Adı')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[core.validators.validate_phone_number], verbose_name='Telefon')),
                ('default_vat_rate', models.DecimalField(decimal_places=2, default=20.0, help_text='Yeni ürünler için varsayılan KDV oranı (%)', max_digits=5, verbose_name='Varsayılan KDV Oranı')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email Bildirimleri')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Email Doğrulandı')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Giriş'), ('logout', 'Çıkış'), ('seller_add', 'Satıcı Hesabı Ekleme'), ('seller_sync', 'Satıcı Senkronizasyonu'), ('cost_update', 'Maliyet Güncelleme'), ('export', 'Rapor İndirme')], max_length=50, verbose_name='Aktivite Tipi')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Ek Bilgiler')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Aktivitesi',
                'verbose_name_plural': 'Kullanıcı Aktiviteleri',
                'db_table': 'user_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
