# Generated by Django 5.1.15 on 2025-12-26 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Hesaplama Tarihi')),
                ('gross_sale_price', models.DecimalField(decimal_places=4, help_text='Birim fiyat × adet (KDV dahil)', max_digits=12, verbose_name='Brüt Satış')),
                ('discount_amount', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='İndirim Tutarı')),
                ('net_sale_price', models.DecimalField(decimal_places=4, help_text='Brüt satış - indirim (KDV dahil)', max_digits=12, verbose_name='Net Satış')),
                ('product_cost_excl_vat', models.DecimalField(decimal_places=4, help_text='Ürün alış maliyeti, KDV hariç', max_digits=12, verbose_name='Ürün Maliyeti (KDV Hariç)')),
                ('purchase_vat_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Alış KDV Oranı')),
                ('purchase_vat', models.DecimalField(decimal_places=4, help_text='product_cost_excl_vat × purchase_vat_rate', max_digits=12, verbose_name="Alış KDV'si")),
                ('product_cost_incl_vat', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Ürün Maliyeti (KDV Dahil)')),
                ('sales_vat_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Satış KDV Oranı')),
                ('sales_vat', models.DecimalField(decimal_places=4, help_text='Hesaplanan KDV (output VAT)', max_digits=12, verbose_name="Satış KDV'si")),
                ('net_sale_price_excl_vat', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Net Satış (KDV Hariç)')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Komisyon Oranı')),
                ('commission_amount_excl_vat', models.DecimalField(decimal_places=4, help_text='net_sale_price_excl_vat × commission_rate', max_digits=12, verbose_name='Komisyon (KDV Hariç)')),
                ('commission_vat_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Komisyon KDV Oranı')),
                ('commission_vat', models.DecimalField(decimal_places=4, max_digits=12, verbose_name="Komisyon KDV'si")),
                ('commission_total', models.DecimalField(decimal_places=4, help_text='Komisyon + KDV', max_digits=12, verbose_name='Komisyon Toplam')),
                ('cargo_cost_excl_vat', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Kargo Maliyeti (KDV Hariç)')),
                ('cargo_vat_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Kargo KDV Oranı')),
                ('cargo_vat', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name="Kargo KDV'si")),
                ('cargo_cost_total', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Kargo Toplam')),
                ('platform_fee_excl_vat', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Platform Ücreti (KDV Hariç)')),
                ('platform_fee_vat_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Platform KDV Oranı')),
                ('platform_fee_vat', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name="Platform KDV'si")),
                ('platform_fee_total', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Platform Toplam')),
                ('withholding_tax_rate', models.DecimalField(decimal_places=4, default=0, help_text='Genellikle 0, bazı durumlar için uygulanır', max_digits=5, verbose_name='Stopaj Oranı')),
                ('withholding_tax', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Stopaj Tutarı')),
                ('total_output_vat', models.DecimalField(decimal_places=4, help_text="Satış KDV'si (output)", max_digits=12, verbose_name='Hesaplanan KDV')),
                ('total_input_vat', models.DecimalField(decimal_places=4, help_text="Alış + Komisyon + Kargo + Platform KDV'si (input)", max_digits=12, verbose_name='İndirilecek KDV')),
                ('net_vat_payable', models.DecimalField(decimal_places=4, help_text='Hesaplanan - İndirilecek KDV (negatif = iade)', max_digits=12, verbose_name='Ödenecek Net KDV')),
                ('total_trendyol_deductions', models.DecimalField(decimal_places=4, help_text='Komisyon + Kargo + Platform (KDV dahil)', max_digits=12, verbose_name='Toplam Trendyol Kesintileri')),
                ('total_cost', models.DecimalField(decimal_places=4, help_text='Tüm maliyet kalemleri toplamı', max_digits=12, verbose_name='Toplam Maliyet')),
                ('net_profit', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Net Kâr')),
                ('profit_margin_percent', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Kâr Marjı (%)')),
                ('is_profitable', models.BooleanField(default=True, verbose_name='Kârlı mı?')),
                ('has_cost_data', models.BooleanField(default=False, help_text='Ürün maliyeti mevcut mu?', verbose_name='Maliyet Verisi Var')),
                ('calculation_version', models.CharField(default='1.0', help_text='Formül versiyon takibi', max_length=10, verbose_name='Hesaplama Versiyonu')),
                ('calculation_notes', models.TextField(blank=True, help_text='Hesaplama sırasında oluşan notlar/uyarılar', verbose_name='Hesaplama Notları')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculation', to='orders.orderitem', verbose_name='Sipariş Kalemi')),
            ],
            options={
                'verbose_name': 'Sipariş Kalemi Hesaplaması',
                'verbose_name_plural': 'Sipariş Kalemi Hesaplamaları',
                'db_table': 'order_item_calculations',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductProfitSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity_sold', models.PositiveIntegerField(default=0, verbose_name='Toplam Satış Adedi')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Toplam Gelir')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Toplam Maliyet')),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Toplam Kâr')),
                ('average_profit_per_item', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kalem Başı Ortalama Kâr')),
                ('average_margin', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Ortalama Marj (%)')),
                ('is_profitable', models.BooleanField(default=True, verbose_name='Kârlı mı?')),
                ('last_30_days_quantity', models.PositiveIntegerField(default=0, verbose_name='Son 30 Gün Satış')),
                ('last_30_days_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Son 30 Gün Kâr')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Hesaplama Tarihi')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profit_summary', to='products.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün Kâr Özeti',
                'verbose_name_plural': 'Ürün Kâr Özetleri',
                'db_table': 'product_profit_summaries',
                'ordering': ['-total_profit'],
            },
        ),
        migrations.CreateModel(
            name='DailyProfitSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Tarih')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Toplam Sipariş')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='Toplam Kalem')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Net satış (KDV dahil)', max_digits=14, verbose_name='Toplam Gelir')),
                ('total_revenue_excl_vat', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Toplam Gelir (KDV Hariç)')),
                ('total_product_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Toplam Ürün Maliyeti')),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Toplam Komisyon')),
                ('total_cargo_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Toplam Kargo')),
                ('total_platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Toplam Platform Ücreti')),
                ('total_vat_payable', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Toplam Ödenecek KDV')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Toplam Maliyet')),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Toplam Kâr')),
                ('average_margin', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Ortalama Marj (%)')),
                ('items_with_cost', models.PositiveIntegerField(default=0, verbose_name='Maliyetli Kalem Sayısı')),
                ('items_without_cost', models.PositiveIntegerField(default=0, verbose_name='Maliyetsiz Kalem Sayısı')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Hesaplama Tarihi')),
                ('seller_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='sellers.selleraccount', verbose_name='Satıcı Hesabı')),
            ],
            options={
                'verbose_name': 'Günlük Kâr Özeti',
                'verbose_name_plural': 'Günlük Kâr Özetleri',
                'db_table': 'daily_profit_summaries',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['seller_account', 'date'], name='daily_profi_seller__002fd6_idx')],
                'unique_together': {('seller_account', 'date')},
            },
        ),
    ]
