# Generated by Django 5.1.15 on 2025-12-26 23:03

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkCostUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('file_name', models.CharField(max_length=255, verbose_name='Dosya Adı')),
                ('file_path', models.FileField(upload_to='bulk_uploads/%Y/%m/', verbose_name='Dosya')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='pending', max_length=20, verbose_name='Durum')),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error_details', models.JSONField(blank=True, default=list, verbose_name='Hata Detayları')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='İşlenme Tarihi')),
                ('seller_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_uploads', to='sellers.selleraccount')),
            ],
            options={
                'verbose_name': 'Toplu Yükleme',
                'verbose_name_plural': 'Toplu Yüklemeler',
                'db_table': 'bulk_cost_uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('barcode', models.CharField(db_index=True, max_length=100, validators=[core.validators.validate_barcode], verbose_name='Barkod')),
                ('product_code', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Model Kodu')),
                ('trendyol_product_id', models.CharField(blank=True, max_length=100, verbose_name='Trendyol Ürün ID')),
                ('title', models.CharField(max_length=500, verbose_name='Ürün Adı')),
                ('brand', models.CharField(blank=True, max_length=255, verbose_name='Marka')),
                ('category', models.CharField(blank=True, max_length=500, verbose_name='Kategori')),
                ('category_id', models.CharField(blank=True, max_length=50, verbose_name='Kategori ID')),
                ('product_cost_excl_vat', models.DecimalField(blank=True, decimal_places=2, help_text='Ürün alış maliyeti, KDV hariç (TL)', max_digits=12, null=True, validators=[core.validators.validate_positive_decimal], verbose_name='Ürün Maliyeti (KDV Hariç)')),
                ('purchase_vat_rate', models.DecimalField(decimal_places=2, default=20.0, help_text='Ürün alış KDV oranı (%)', max_digits=5, validators=[core.validators.validate_percentage], verbose_name='Alış KDV Oranı')),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Trendyol kategori komisyon oranı (%). Boşsa satıcı varsayılanı kullanılır.', max_digits=5, null=True, validators=[core.validators.validate_percentage], verbose_name='Komisyon Oranı')),
                ('sales_vat_rate', models.DecimalField(decimal_places=2, default=20.0, help_text='Satış KDV oranı (%)', max_digits=5, validators=[core.validators.validate_percentage], verbose_name='Satış KDV Oranı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('has_cost_data', models.BooleanField(default=False, help_text='Maliyet bilgisi girilmiş mi?', verbose_name='Maliyet Verisi Var')),
                ('cost_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Maliyet Güncelleme Tarihi')),
                ('last_order_date', models.DateTimeField(blank=True, null=True, verbose_name='Son Sipariş Tarihi')),
                ('total_quantity_sold', models.PositiveIntegerField(default=0, verbose_name='Toplam Satış Adedi')),
                ('seller_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sellers.selleraccount', verbose_name='Satıcı Hesabı')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'db_table': 'products',
                'ordering': ['-last_order_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProductCostHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_excl_vat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Maliyet (KDV Hariç)')),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='KDV Oranı')),
                ('effective_date', models.DateField(help_text='Bu maliyetin geçerli olduğu tarih', verbose_name='Geçerlilik Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_history', to='products.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Maliyet Geçmişi',
                'verbose_name_plural': 'Maliyet Geçmişleri',
                'db_table': 'product_cost_history',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller_account', 'barcode'], name='products_seller__1d7e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller_account', 'product_code'], name='products_seller__7fd129_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('seller_account', 'barcode')},
        ),
    ]
