# Generated by Django 5.1.15 on 2025-12-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=100, verbose_name='Renk'),
        ),
        migrations.AddField(
            model_name='product',
            name='desi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Desi'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Ürün Görseli URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=50, verbose_name='Beden'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stok'),
        ),
    ]
